// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitor/visitor.message.proto

package com.ljzn.grpc.visitor;

public interface CheckOutMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VisitorSystem_cq.CheckOutMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *访问ID
   * </pre>
   *
   * <code>string visitId = 1;</code>
   */
  java.lang.String getVisitId();
  /**
   * <pre>
   *访问ID
   * </pre>
   *
   * <code>string visitId = 1;</code>
   */
  com.google.protobuf.ByteString
      getVisitIdBytes();

  /**
   * <pre>
   *签离设备ID
   * </pre>
   *
   * <code>string checkOutDeviceId = 2;</code>
   */
  java.lang.String getCheckOutDeviceId();
  /**
   * <pre>
   *签离设备ID
   * </pre>
   *
   * <code>string checkOutDeviceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheckOutDeviceIdBytes();

  /**
   * <pre>
   *签离时间
   * </pre>
   *
   * <code>int64 checkOutTime = 3;</code>
   */
  long getCheckOutTime();

  /**
   * <pre>
   *本系统分配的ID
   * </pre>
   *
   * <code>int32 belongId = 4;</code>
   */
  int getBelongId();
}
