// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitor/visitor.message.proto

package com.ljzn.grpc.visitor;

public interface VisitInfoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VisitorSystem_cq.VisitInfoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *访问ID
   * </pre>
   *
   * <code>string visitId = 1;</code>
   */
  java.lang.String getVisitId();
  /**
   * <pre>
   *访问ID
   * </pre>
   *
   * <code>string visitId = 1;</code>
   */
  com.google.protobuf.ByteString
      getVisitIdBytes();

  /**
   * <pre>
   *被访人ID
   * </pre>
   *
   * <code>int32 employeeId = 2;</code>
   */
  int getEmployeeId();

  /**
   * <pre>
   *访客ID
   * </pre>
   *
   * <code>string visitorId = 3;</code>
   */
  java.lang.String getVisitorId();
  /**
   * <pre>
   *访客ID
   * </pre>
   *
   * <code>string visitorId = 3;</code>
   */
  com.google.protobuf.ByteString
      getVisitorIdBytes();

  /**
   * <pre>
   *访客姓名
   * </pre>
   *
   * <code>string visitorName = 4;</code>
   */
  java.lang.String getVisitorName();
  /**
   * <pre>
   *访客姓名
   * </pre>
   *
   * <code>string visitorName = 4;</code>
   */
  com.google.protobuf.ByteString
      getVisitorNameBytes();

  /**
   * <pre>
   *访原因
   * </pre>
   *
   * <code>int32 reasonId = 5;</code>
   */
  int getReasonId();

  /**
   * <pre>
   *现场照片
   * </pre>
   *
   * <code>bytes cameraPhoto = 6;</code>
   */
  com.google.protobuf.ByteString getCameraPhoto();

  /**
   * <pre>
   *签入设备Id
   * </pre>
   *
   * <code>string checkInDeviceId = 7;</code>
   */
  java.lang.String getCheckInDeviceId();
  /**
   * <pre>
   *签入设备Id
   * </pre>
   *
   * <code>string checkInDeviceId = 7;</code>
   */
  com.google.protobuf.ByteString
      getCheckInDeviceIdBytes();

  /**
   * <pre>
   *签入时间(秒级时间戳)
   * </pre>
   *
   * <code>int64 checkInTime = 8;</code>
   */
  long getCheckInTime();

  /**
   * <pre>
   *签离设备ID
   * </pre>
   *
   * <code>string checkOutDeviceId = 9;</code>
   */
  java.lang.String getCheckOutDeviceId();
  /**
   * <pre>
   *签离设备ID
   * </pre>
   *
   * <code>string checkOutDeviceId = 9;</code>
   */
  com.google.protobuf.ByteString
      getCheckOutDeviceIdBytes();

  /**
   * <pre>
   *签出时间(秒级时间戳)
   * </pre>
   *
   * <code>int64 checkOutTime = 10;</code>
   */
  long getCheckOutTime();

  /**
   * <pre>
   * 状态(0访问中 ,1 已签离)
   * </pre>
   *
   * <code>int32 state = 11;</code>
   */
  int getState();

  /**
   * <pre>
   *备注
   * </pre>
   *
   * <code>string comment = 12;</code>
   */
  java.lang.String getComment();
  /**
   * <pre>
   *备注
   * </pre>
   *
   * <code>string comment = 12;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <pre>
   *操作
   * </pre>
   *
   * <code>int32 action = 15;</code>
   */
  int getAction();

  /**
   * <pre>
   *版本
   * </pre>
   *
   * <code>int64 version = 16;</code>
   */
  long getVersion();

  /**
   * <pre>
   *本系统分配的ID
   * </pre>
   *
   * <code>int32 belongId = 17;</code>
   */
  int getBelongId();
}
